### ISSUE TITLE
CoreProtect Console Errors

### ISSUE THREAD

**Issue by ego-tistical** [ego-tistical/di.mcserver.upgrade.test#6]
[14:49:29] [Thread-20/WARN]: org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
[14:49:29] [Thread-20/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:941)
[14:49:29] [Thread-20/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:953)
[14:49:29] [Thread-20/WARN]: 	at org.sqlite.core.DB.execute(DB.java:857)
[14:49:29] [Thread-20/WARN]: 	at org.sqlite.core.DB.executeUpdate(DB.java:895)
[14:49:29] [Thread-20/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
[14:49:29] [Thread-20/WARN]: 	at net.coreprotect.database.Database.insertEntity(Database.java:313)
[14:49:29] [Thread-20/WARN]: 	at net.coreprotect.database.Logger.log_entity_kill(Logger.java:397)
[14:49:29] [Thread-20/WARN]: 	at net.coreprotect.consumer.Process.processEntityKill(Process.java:346)
[14:49:29] [Thread-20/WARN]: 	at net.coreprotect.consumer.Process.processConsumer(Process.java:186)
[14:49:29] [Thread-20/WARN]: 	at net.coreprotect.consumer.Consumer.run(Consumer.java:124)
[14:49:29] [Thread-20/WARN]: 	at java.lang.Thread.run(Unknown Source)
[14:49:29] [Thread-20/WARN]: org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
[14:49:29] [Thread-20/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:941)
[14:49:29] [Thread-20/WARN]: 	at org.sqlite.core.DB.newSQLException(DB.java:953)
[14:49:29] [Thread-20/WARN]: 	at org.sqlite.core.DB.execute(DB.java:857)
[14:49:29] [Thread-20/WARN]: 	at org.sqlite.core.DB.executeUpdate(DB.java:895)
[14:49:29] [Thread-20/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
[14:49:29] [Thread-20/WARN]: 	at net.coreprotect.database.Database.insertBlock(Database.java:245)
[14:49:29] [Thread-20/WARN]: 	at net.coreprotect.database.Logger.log_entity_kill(Logger.java:402)
[14:49:29] [Thread-20/WARN]: 	at net.coreprotect.consumer.Process.processEntityKill(Process.java:346)
[14:49:29] [Thread-20/WARN]: 	at net.coreprotect.consumer.Process.processConsumer(Process.java:186)
[14:49:29] [Thread-20/WARN]: 	at net.coreprotect.consumer.Consumer.run(Consumer.java:124)
[14:49:29] [Thread-20/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by ego-tistical** [comment]
Possible need to upgrade from CoreProtect-2.17.5.jar -> 2.18.2

https://www.spigotmc.org/resources/coreprotect.8631/

**Comment by Kranky916** [comment]
2.17.5 was for 1.14 and 2.18.2 is for 1.15.2

**Comment by ego-tistical** [comment]
Deleted db file
